import dcp
import json

# Initialize DCP
dcp.init()

# --- Generated Work Function ---
{{FUNCTION_CODE}}

# --- Input Set ---
# This will be populated with the input data for the job
inputSet = {{INPUT_SET}}

# --- Additional Arguments ---
# This will be populated with static arguments shared by all slices
args = []

# --- DCP Job Configuration ---
job = dcp.compute_for(inputSet, {{FUNCTION_NAME}}, args)

# Configuration
job.modules = {{MODULES}}
job.computeGroups = [{'joinKey': 'demo', 'joinSecret': 'dcp'}]
job.public.name = '{{JOB_NAME}}'
job.public.description = 'Generated by dcipify'

# Event Listeners
job.on('accepted', lambda _: print(f"DCP Job ID: {job.id}\nAwaiting results..."))
job.on('result',   lambda r: print(f"    ✓ result slice: {int(r.sliceNumber)}, value: {r.result}"))
job.on('error',    lambda e: print(f"    [!] Error: {json.dumps(e)}"))

# Execute
print(f"[*] Dispatching job: {job.public.name}...")
job.exec()
results = job.wait()

print("\n>>> All results received.")
print(results)
